import NavBar from '@/components/NavBar';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { config } from 'dotenv';
config();

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Sol's ChessApp",
  description: "Generated by Sol's ChessApp",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className='h-screen overflow-hidden'>
      <body className={`${inter.className} h-screen`}>
        {/* Navbar */}
        <div className='h-[5vh] w-full fixed top-0 z-50'>
          <NavBar />
        </div>

        {/* Main Content */}
        <div className='h-[95vh] overflow-y-auto flex flex-col mt-[5vh]'>
          {children}
        </div>
      </body>
    </html>
  );
}
